[package]
name = "synclite"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
# Workspace
log = { path = "crates/log" }
common = { path = "crates/common" }
app = { path = "crates/app" }
workspace = { path = "crates/workspace" }
p2p = { path = "crates/p2p" }
# General
tokio = { version = "1.49.0", features = ["full"] }
uuid = {version = "1.19.0", features = ["v4", "serde"]}
chrono = { version = "0.4.30", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
dirs = "6.0"
anyhow = "1.0.100"
colored = "3.0.0"
# Files
notify = "8.2.0"
# Network
local-ip-address = "0.6.8"
mdns-sd = "0.17.1"
# Cli
dsl_cli = "0.3.0"


[dependencies]
# Workspace
log = { path = "crates/log" }
common = { path = "crates/common" }
app = { path = "crates/app" }
workspace = { path = "crates/workspace" }
p2p = { path = "crates/p2p" }
# General
anyhow = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
colored = { workspace = true }
# Files
notify = { workspace = true }
# Network
mdns-sd = { workspace = true }
local-ip-address = { workspace = true }
# Cli
dsl_cli = { workspace = true }